import type { Metadata } from "next";
import '../../styles/globals.css';
import Providers from "@/app/providers";


export const metadata: Metadata = {
  title: "Growthyflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="flex flex-col flex-1">
        <main className="flex-1">{children}</main>
      </div>
  );
}
