import { Assessment } from "./types";

export const STORAGE_KEY = "growthyflow_assessments";

export const DEFAULT_ASSESSMENTS: Assessment[] = [
  {
    id: 1,
    category: "Web",
    title: "Web Development",
    description:
      "Develop a responsive and user-friendly website that works smoothly across desktop, tablet, and mobile devices. The task includes designing the layout, building core pages, adding, optimizing performance, and ensuring the site is easy to update and maintain.",
    status: "In Progress",
    startDate: "05 Mar 2026",
    endDate: "13 Mar 2026",
    assignedBy: "Tan Dara",
    points: 100,
    requirements: [
      "HTML, CSS, and JavaScript implementation",
      "Responsive layout",
      "Cross-browser compatibility",
      "Interactive buttons, forms, menus, or sliders",
      "Clean and reusable code",
      "Accessibility-friendly design",
      "Pixel-accurate design conversion",
      "Optimized images and assets",
    ],
    attachments: [
      {
        id: 1,
        name: "Project Requirements",
        type: "docx",
        size: "1.2 MB",
        url: "#",
        action: "Download",
      },
      {
        id: 2,
        name: "Project Setup Guidelines",
        type: "youtube",
        url: "https://youtube.com",
        action: "Open",
      },
      {
        id: 3,
        name: "prerequisite-web-001",
        type: "zip",
        size: "5.2 MB",
        url: "#",
        action: "Download",
      },
    ],
    gradingRubric: [
      { label: "Code Quality", points: 30 },
      { label: "Responsiveness", points: 25 },
      { label: "Design Accuracy", points: 25 },
      { label: "Documentation", points: 20 },
    ],
    passingScore: 60,
    requiredDailyMinutes: 60,
    daysUntilDeadline: 2,
  },
  {
    id: 2,
    category: "Java",
    title: "Java Mini-Project 002",
    description:
      "Please read the instruction in the Google Docs which is the Java Mini-Project 002 - Instruction carefully and submit your GitHub repository.",
    status: "In Progress",
    startDate: "11 Mar 2026",
    endDate: "14 Mar 2026",
    assignedBy: "Tan Dara",
    points: 100,
    requirements: [
      "Follow OOP principles",
      "Include at least 3 classes",
      "Submit GitHub repository link",
      "Add README with setup instructions",
      "Unit tests for core functions",
    ],
    attachments: [
      {
        id: 1,
        name: "Java Mini-Project 002 Instruction",
        type: "docx",
        size: "0.8 MB",
        url: "#",
        action: "Download",
      },
      {
        id: 2,
        name: "Sample Project Structure",
        type: "zip",
        size: "2.1 MB",
        url: "#",
        action: "Download",
      },
    ],
    gradingRubric: [
      { label: "OOP Design", points: 30 },
      { label: "Functionality", points: 35 },
      { label: "Code Style", points: 20 },
      { label: "README", points: 15 },
    ],
    passingScore: 60,
    requiredDailyMinutes: 90,
    daysUntilDeadline: 5,
  },
  {
    id: 3,
    category: "UX/UI",
    title: "Figma Design",
    description:
      "Design a responsive landing page in Figma with a clean and modern layout. Include key sections such as hero, features, testimonials, and a call-to-action footer.",
    status: "Closed",
    startDate: "01 Apr 2026",
    endDate: "03 Apr 2026",
    assignedBy: "Tan Dara",
    points: 100,
    requirements: [
      "Design in Figma using auto-layout",
      "Include desktop and mobile frames",
      "Hero section with CTA button",
      "Features section with icons",
      "Testimonials section",
      "Footer with navigation links",
      "Consistent color and typography system",
      "Export assets at 2x resolution",
    ],
    attachments: [
      {
        id: 1,
        name: "Design Brief",
        type: "pdf",
        size: "0.5 MB",
        url: "#",
        action: "Download",
      },
      {
        id: 2,
        name: "Brand Guidelines",
        type: "pdf",
        size: "3.4 MB",
        url: "#",
        action: "Download",
      },
      {
        id: 3,
        name: "Design Reference Video",
        type: "youtube",
        url: "https://youtube.com",
        action: "Open",
      },
    ],
    gradingRubric: [
      { label: "Visual Design", points: 35 },
      { label: "Layout & Spacing", points: 25 },
      { label: "Responsiveness", points: 20 },
      { label: "Assets & Export", points: 20 },
    ],
    passingScore: 60,
    requiredDailyMinutes: 45,
    daysUntilDeadline: 0,
  },
];
