import type { Metadata } from "next";
import { Fredoka, Geist } from "next/font/google";
import '../../../styles/globals.css';
import { cn } from "@/lib/utils";
import Providers from "@/app/providers";



const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const fredoka = Fredoka({
  variable: "--font-fredoka-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Growthyflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fredoka.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
      
          <main>
            <Providers>
            {children}
            </Providers>
          </main>
        
      </body>
    </html>
  );
}
